TLP_ENABLE=1
TLP_AUTO_SWITCH=2

# AC — максимальная производительность
TLP_PROFILE_AC=PRF
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_BOOST_ON_AC=1
CPU_HWP_DYN_BOOST_ON_AC=1
PLATFORM_PROFILE_ON_AC=performance

# Battery — максимальная экономия
TLP_PROFILE_BAT=SAV
CPU_ENERGY_PERF_POLICY_ON_BAT=power
CPU_BOOST_ON_BAT=0
CPU_HWP_DYN_BOOST_ON_BAT=0
PLATFORM_PROFILE_ON_BAT=low-power
