# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Instructions
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[colors.primary]

background = "#2a2c39"
foreground = "#f8f8f2"
bright_foreground = "#ffffff"

[colors.cursor]

text = "#2a2c39"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#44475a"

[colors.normal]

black = "#21222c"
red = "#ff5555"
green = "#25a487"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]

black = "#9a9996"
red = "#ff6e6e"
green = "#3ca58c"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.search.matches]

foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]

foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]

background = "#2a2c39"
foreground = "#f8f8f2"

[colors.hints.start]

foreground = "#2a2c39"
background = "#f1fa8c"

[colors.hints.end]

foreground = "#f1fa8c"
background = "#2a2c39"
