listener {
    timeout = 1800
    on-timeout = playerctl --all-players pause & pidof hyprlock || hyprlock & hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
