general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = playerctl --all-players pause && loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 600
    on-timeout = playerctl --all-players pause && loginctl lock-session && systemctl suspend
}

listener {
    event = lid
    on-close = playerctl --all-players pause && loginctl lock-session && systemctl suspend
}
